import assert from "node:assert/strict";
import test from "node:test";
import type { LlmProvider, ToolGateway } from "@instagram-agent/contracts";
import { InMemoryAuditRepository, InstrumentedLlmProvider, InstrumentedToolGateway, MetricsRegistry, StructuredLogger, type StructuredLog } from "./observability.js";
import { redact, scanSecrets } from "./security.js";

test("central redaction removes seeded secrets and private content at every depth", () => { const value = redact({ authorization: "Bearer secret-token-12345", nested: { password: "hunter2", arguments: { text: "private comment", postId: "p1" } }, safeId: "task-1" }); assert.equal(value.authorization, "[REDACTED_SECRET]"); assert.equal(value.nested.password, "[REDACTED_SECRET]"); assert.equal(value.nested.arguments, "[REDACTED_PRIVATE_DATA]"); assert.equal(value.safeId, "task-1"); const findings = scanSecrets("SAFE=value\nAPI_KEY=seeded-secret-123456\nAuthorization: Bearer abcdefghijklmnop"); assert.deepEqual(findings.map(({ name, line }) => ({ name, line })), [{ name: "generic_secret", line: 2 }, { name: "bearer_token", line: 3 }]); assert.ok(findings.every((item) => !JSON.stringify(item).includes("seeded-secret"))); });
test("controlled tool failure is correlated in logs, metrics, and redacted audit history", async () => { let clock = 1_000; const logs: StructuredLog[] = []; let sequence = 0; const metrics = new MetricsRegistry(); const audit = new InMemoryAuditRepository(); const instrumentation = { logger: new StructuredLogger("mcp-client", { write: (record) => logs.push(record) }, () => new Date(clock).toISOString()), metrics, audit, now: () => (clock += 25), id: () => `audit-${++sequence}` }; const inner: ToolGateway = { listTools: async () => [], invoke: async (_user, invocation) => ({ invocationId: invocation.invocationId, ok: false, error: { code: "mcp_timeout", message: "Bearer seeded-secret-123456", retryable: true } }) }; const result = await new InstrumentedToolGateway(inner, "task-1", instrumentation).invoke("user-1", { invocationId: "inv-1", name: "instagram_get_posts", arguments: { text: "private", token: "seeded-secret-123456" } }); assert.equal(result.ok, false); assert.deepEqual(logs[0] && { taskId: logs[0].taskId, invocationId: logs[0].invocationId, status: logs[0].status, retry: logs[0].retry }, { taskId: "task-1", invocationId: "inv-1", status: "failed", retry: 1 }); const snapshot = metrics.snapshot(); assert.equal(snapshot.counters["errors_total{code=mcp_timeout,component=tool}"], 1); assert.equal(snapshot.durations["tool_duration_ms{tool=instagram_get_posts}"]?.count, 1); const history = await audit.forTask("user-1", "task-1"); assert.equal(history[0]?.invocationId, "inv-1"); assert.doesNotMatch(JSON.stringify({ logs, history }), /seeded-secret|private/); });
test("model decisions record usage and failures without prompt content", async () => { const logs: StructuredLog[] = []; const metrics = new MetricsRegistry(); const audit = new InMemoryAuditRepository(); const instrumentation = { logger: new StructuredLogger("ollama", { write: (record) => logs.push(record) }), metrics, audit, now: () => 1_000, id: () => "audit-model" }; const provider: LlmProvider = { generateDecision: async () => ({ decision: { kind: "cannot_continue", reason: "No safe action", rationaleSummary: "No tool", userMessage: "Stopped" }, model: "local", usage: { inputTokens: 5 } }) }; await new InstrumentedLlmProvider(provider, "user", "task", instrumentation).generateDecision({ messages: [{ role: "user", content: "private prompt" }], decisionSchema: {} }); assert.equal(metrics.snapshot().counters["model_decisions_total{model=local,status=succeeded}"], 1); assert.doesNotMatch(JSON.stringify(await audit.forTask("user", "task")), /private prompt/); });
