import assert from "node:assert/strict";
import test from "node:test";
import { createTaskState, transitionTask, type AgentTaskState } from "./state.js";
import { classifyFailure, recoverInterruptedTasks, withRetry, type RecoveryStore } from "./reliability.js";

test("taxonomy retries only transient, timeout, and rate-limit failures", () => { for (const code of ["invalid_tool_input", "permission_denied", "authentication_required", "missing_model", "cancelled"]) assert.equal(classifyFailure(code).retryable, false, code); for (const code of ["mcp_connection_error", "provider_timeout", "rate_limited"]) assert.equal(classifyFailure(code).retryable, true, code); assert.equal(classifyFailure("unrecognized").class, "permanent"); });
test("capped backoff obeys attempts, jitter, and retry budget with a fake clock", async () => { let now = 0; const sleeps: number[] = []; const attempts: number[] = []; const result = await withRetry(async (attempt) => { attempts.push(attempt); if (attempt < 3) throw Object.assign(new Error("offline"), { code: "offline" }); return "ok"; }, (error) => (error as { code: string }).code, { maximumAttempts: 4, baseDelayMs: 100, maximumDelayMs: 150, jitterRatio: 0, budgetMs: 500 }, { now: () => now, random: () => .5, sleep: async (delay) => { sleeps.push(delay); now += delay; } }); assert.equal(result, "ok"); assert.deepEqual(attempts, [1, 2, 3]); assert.deepEqual(sleeps, [100, 150]); let budgetAttempts = 0; await assert.rejects(withRetry(async () => { budgetAttempts += 1; throw Object.assign(new Error("offline"), { code: "offline" }); }, (error) => (error as { code: string }).code, { maximumAttempts: 9, baseDelayMs: 100, maximumDelayMs: 500, jitterRatio: 0, budgetMs: 50 }, { now: () => 0, sleep: async () => {} })); assert.equal(budgetAttempts, 1); });
test("backoff cancellation is immediate", async () => { const controller = new AbortController(); let sleeping = false; const promise = withRetry(async () => { throw Object.assign(new Error("timeout"), { code: "timeout" }); }, (error) => (error as { code: string }).code, { maximumAttempts: 3, baseDelayMs: 10, maximumDelayMs: 10, jitterRatio: 0, budgetMs: 100 }, { signal: controller.signal, sleep: async (_delay, signal) => { sleeping = true; await new Promise<void>((_resolve, reject) => signal?.addEventListener("abort", () => reject(signal.reason), { once: true })); } }); while (!sleeping) await new Promise((resolve) => setImmediate(resolve)); controller.abort(new Error("cancelled")); await assert.rejects(promise, /cancelled/); });
test("crash recovery resumes running work once and leaves approvals paused without duplicating steps", async () => { const at = "2026-08-25T01:00:00.000Z"; const running = transitionTask(transitionTask(createTaskState({ taskId: "run", userId: "u", text: "run" }, "2026-08-25T00:00:00.000Z"), { type: "started", at: "2026-08-25T00:00:01.000Z" }), { type: "step_started", at: "2026-08-25T00:00:02.000Z", stepId: "s1", iteration: 1, action: "read" }); const approval = transitionTask(transitionTask(createTaskState({ taskId: "approval", userId: "u", text: "approve" }, "2026-08-25T00:00:00.000Z"), { type: "started", at: "2026-08-25T00:00:01.000Z" }), { type: "approval_required", at: "2026-08-25T00:00:02.000Z", reason: "paused" }); const records = new Map([[running.taskId, running], [approval.taskId, approval]]); const store: RecoveryStore = { findRecoverable: async (before) => [...records.values()].filter((state) => (state.status === "running" || state.status === "approval_required") && state.updatedAt < before), replaceIfRevision: async (state, revision) => { const current = records.get(state.taskId); if (current?.revision !== revision) return false; records.set(state.taskId, state); return true; } }; const queued: AgentTaskState[] = []; const first = await recoverInterruptedTasks(store, async (state) => { queued.push(state); }, at); assert.deepEqual(first, { resumed: ["run"], awaitingApproval: ["approval"], conflicts: [] }); assert.equal(queued[0]?.steps.length, 1); assert.equal(records.get("approval")?.status, "approval_required"); assert.deepEqual(await recoverInterruptedTasks(store, async (state) => { queued.push(state); }, at), { resumed: [], awaitingApproval: [], conflicts: [] }); assert.equal(queued.length, 1); });
