import type { AgentTaskState } from "./state.js";

export type FailureClass = "validation" | "permission" | "authentication" | "transient" | "rate_limit" | "timeout" | "permanent" | "cancelled";
export interface ClassifiedFailure { readonly class: FailureClass; readonly retryable: boolean; readonly reason: string }
const groups: Record<FailureClass, readonly string[]> = {
  validation: ["invalid", "schema", "malformed"], permission: ["permission", "denied", "prohibited", "origin_denied"], authentication: ["auth", "session", "unauthorized"],
  transient: ["offline", "connection", "temporarily_unavailable", "provider_error", "mcp_connect_failed"], rate_limit: ["rate_limit", "too_many_requests"], timeout: ["timeout", "deadline"], permanent: ["not_found", "missing_model", "unsupported", "permanent"], cancelled: ["cancel", "abort"],
};
export function classifyFailure(code: string): ClassifiedFailure { const normalized = code.toLowerCase(); for (const [kind, patterns] of Object.entries(groups) as Array<[FailureClass, readonly string[]]>) if (patterns.some((pattern) => normalized.includes(pattern))) return { class: kind, retryable: kind === "transient" || kind === "rate_limit" || kind === "timeout", reason: `${kind} failures ${kind === "transient" || kind === "rate_limit" || kind === "timeout" ? "may be retried within budget" : "must not be retried"}` }; return { class: "permanent", retryable: false, reason: "Unknown failures default to permanent" }; }

export interface RetryPolicy { readonly maximumAttempts: number; readonly baseDelayMs: number; readonly maximumDelayMs: number; readonly jitterRatio: number; readonly budgetMs: number }
export interface RetryAttempt { readonly attempt: number; readonly delayMs: number; readonly elapsedMs: number; readonly code: string }
export interface RetryOptions { readonly signal?: AbortSignal; readonly sleep?: (milliseconds: number, signal?: AbortSignal) => Promise<void>; readonly random?: () => number; readonly now?: () => number; readonly onRetry?: (attempt: RetryAttempt) => void }
export const defaultRetryPolicy: RetryPolicy = { maximumAttempts: 3, baseDelayMs: 250, maximumDelayMs: 5_000, jitterRatio: .2, budgetMs: 15_000 };
const defaultSleep = (milliseconds: number, signal?: AbortSignal) => new Promise<void>((resolve, reject) => { if (signal?.aborted) return reject(signal.reason); const timer = setTimeout(resolve, milliseconds); signal?.addEventListener("abort", () => { clearTimeout(timer); reject(signal.reason); }, { once: true }); });
export async function withRetry<T>(operation: (attempt: number) => Promise<T>, codeOf: (error: unknown) => string, policy: RetryPolicy = defaultRetryPolicy, options: RetryOptions = {}): Promise<T> { const started = (options.now ?? Date.now)(); let last: unknown; for (let attempt = 1; attempt <= policy.maximumAttempts; attempt += 1) { if (options.signal?.aborted) throw options.signal.reason; try { return await operation(attempt); } catch (error) { last = error; const code = codeOf(error); const classification = classifyFailure(code); const elapsed = (options.now ?? Date.now)() - started; if (!classification.retryable || attempt >= policy.maximumAttempts) throw error; const exponential = Math.min(policy.maximumDelayMs, policy.baseDelayMs * 2 ** (attempt - 1)); const jitter = exponential * policy.jitterRatio * ((options.random ?? Math.random)() * 2 - 1); const delayMs = Math.max(0, Math.round(exponential + jitter)); if (elapsed + delayMs > policy.budgetMs) throw error; options.onRetry?.({ attempt, delayMs, elapsedMs: elapsed, code }); await (options.sleep ?? defaultSleep)(delayMs, options.signal); } } throw last; }

export interface RecoveryStore { findRecoverable(before: string): Promise<readonly AgentTaskState[]>; replaceIfRevision(state: AgentTaskState, expectedRevision: number): Promise<boolean> }
export interface RecoveryResult { readonly resumed: readonly string[]; readonly awaitingApproval: readonly string[]; readonly conflicts: readonly string[] }
export async function recoverInterruptedTasks(store: RecoveryStore, enqueue: (state: AgentTaskState) => Promise<void>, at = new Date().toISOString()): Promise<RecoveryResult> { const resumed: string[] = []; const awaitingApproval: string[] = []; const conflicts: string[] = []; for (const state of await store.findRecoverable(at)) { const next: AgentTaskState = state.status === "running" ? { ...state, status: "queued", currentAction: null, updatedAt: at, revision: state.revision + 1 } : { ...state, updatedAt: at, revision: state.revision + 1 }; if (!await store.replaceIfRevision(next, state.revision)) { conflicts.push(state.taskId); continue; } if (next.status === "queued") { await enqueue(next); resumed.push(next.taskId); } else awaitingApproval.push(next.taskId); } return { resumed, awaitingApproval, conflicts }; }
