import { describe, expect, it, vi } from "vitest";
import { ApiClient, ApiError } from "./api-client.js";
const response = (body: unknown, status = 200) => new Response(JSON.stringify(body), { status, headers: { "content-type": "application/json" } });
describe("ApiClient", () => {
  it("adds authentication and returns typed data", async () => { const fetcher = vi.fn(async (_url, init) => { expect(new Headers(init?.headers).get("authorization")).toBe("Bearer secret"); return response({ data: { taskId: "one" } }); }); const result = await new ApiClient({ token: () => "secret", fetch: fetcher as typeof fetch }).task("one"); expect(result.taskId).toBe("one"); });
  it("normalizes validation errors with request IDs", async () => { const client = new ApiClient({ token: () => "x", fetch: async () => response({ error: { code: "invalid_goal", message: "Goal is invalid", requestId: "req-1" } }, 400) }); await expect(client.createTask("")).rejects.toEqual(expect.objectContaining({ code: "invalid_goal", status: 400, requestId: "req-1" })); });
  it("normalizes authorization failures", async () => { const client = new ApiClient({ token: () => "bad", fetch: async () => response({ error: { code: "invalid_session", message: "Expired" } }, 401) }); await expect(client.analytics()).rejects.toBeInstanceOf(ApiError); await expect(client.analytics()).rejects.toMatchObject({ code: "invalid_session" }); });
  it("normalizes network failures and honors cancellation", async () => { const client = new ApiClient({ token: () => "x", fetch: async () => { throw new TypeError("offline"); } }); await expect(client.reviews()).rejects.toMatchObject({ code: "network_error" }); const controller = new AbortController(); controller.abort(); await expect(client.task("one", controller.signal)).rejects.toBeInstanceOf(TypeError); });
  it("unwraps named profile content", async () => { const client = new ApiClient({ token: () => "x", fetch: async () => response({ data: { username: "areeha_khan10", displayName: "Areeha", posts: [], nextCursor: null, collectedAt: "2026-08-26T00:00:00Z" } }) }); await expect(client.collectProfile("areeha_khan10")).resolves.toMatchObject({ username: "areeha_khan10", posts: [] }); });
});
