import type { Analytics, Approval, ConnectionList, ConnectionResult, ProfileContent, ReviewItem, Task, TaskEvent } from "./types.js";
export class ApiError extends Error { constructor(readonly code: string, message: string, readonly status: number, readonly requestId?: string) { super(message); this.name = "ApiError"; } }
export interface ApiClientOptions { readonly baseUrl?: string; readonly token: () => string; readonly fetch?: typeof fetch }
export class ApiClient {
  readonly #base: string; readonly #token: () => string; readonly #fetch: typeof fetch;
  constructor(options: ApiClientOptions) { this.#base = options.baseUrl ?? ""; this.#token = options.token; this.#fetch = options.fetch ?? globalThis.fetch.bind(globalThis); }
  async #request<T>(path: string, init: RequestInit = {}, signal?: AbortSignal): Promise<T> { let response: Response; const headers = new Headers(init.headers); headers.set("authorization", `Bearer ${this.#token()}`); if (init.body) headers.set("content-type", "application/json"); try { response = await this.#fetch(`${this.#base}${path}`, { ...init, headers, ...(signal ? { signal } : {}) }); } catch (error) { if (signal?.aborted) throw error; throw new ApiError("network_error", "Could not reach the local API", 0); } const body = await response.json().catch(() => ({})) as { data?: T; error?: { code?: string; message?: string; requestId?: string } }; if (!response.ok) throw new ApiError(body.error?.code ?? "http_error", body.error?.message ?? `Request failed (${response.status})`, response.status, body.error?.requestId); return body.data as T; }
  createTask(goal: string, signal?: AbortSignal) { return this.#request<Task>("/api/agent/tasks", { method: "POST", body: JSON.stringify({ goal }) }, signal); }
  task(id: string, signal?: AbortSignal) { return this.#request<Task>(`/api/agent/tasks/${encodeURIComponent(id)}`, {}, signal); }
  cancel(id: string, signal?: AbortSignal) { return this.#request<Task>(`/api/agent/tasks/${encodeURIComponent(id)}/cancel`, { method: "POST" }, signal); }
  approval(id: string, signal?: AbortSignal) { return this.#request<Approval>(`/api/agent/tasks/${encodeURIComponent(id)}/approval`, {}, signal); }
  decide(taskId: string, approval: Approval, decision: "approve" | "reject", signal?: AbortSignal) { return this.#request<{ status: string; task: Task }>(`/api/agent/tasks/${encodeURIComponent(taskId)}/approvals/${encodeURIComponent(approval.requestId)}`, { method: "POST", body: JSON.stringify({ token: approval.token, decision }) }, signal); }
  analytics(category = "", severity = "", signal?: AbortSignal) { const query = new URLSearchParams({ ...(category ? { category } : {}), ...(severity ? { severity } : {}) }); return this.#request<Analytics>(`/api/analytics/complaints?${query}`, {}, signal); }
  async comments(ids: readonly string[], signal?: AbortSignal) { const chunks: string[][] = []; for (let index = 0; index < ids.length; index += 100) chunks.push(ids.slice(index, index + 100) as string[]); const pages = await Promise.all(chunks.map((chunk) => this.#request<Record<string, unknown>[]>(`/api/comments?limit=100&commentIds=${encodeURIComponent(chunk.join(","))}`, {}, signal))); const found = new Map(pages.flat().map((item) => [String(item.commentId), item])); return ids.map((id) => found.get(id) ?? { commentId: id, text: "Source record unavailable" }); }
  reviews(signal?: AbortSignal) { return this.#request<ReviewItem[]>("/api/reviews?limit=100", {}, signal); }
  correct(commentId: string, correction: Record<string, unknown>, signal?: AbortSignal) { return this.#request<ReviewItem>(`/api/reviews/${encodeURIComponent(commentId)}`, { method: "PATCH", body: JSON.stringify({ correction }) }, signal); }
  collect(cursor?: string, followerCursor?: string, signal?: AbortSignal) { return this.#request<ConnectionResult>("/api/instagram/following-comments", { method: "POST", body: JSON.stringify({ accountsPerBatch: 5, postsPerAccount: 2, commentsPerPost: 10, ...(cursor ? { cursor } : {}), ...(followerCursor ? { followerCursor } : {}) }) }, signal); }
  collectProfile(username: string, cursor?: string, signal?: AbortSignal) { return this.#request<ProfileContent>("/api/instagram/profile-content", { method: "POST", body: JSON.stringify({ username, ...(cursor ? { cursor } : {}) }) }, signal); }
  connections(list: "followers" | "following", cursor?: string, signal?: AbortSignal) { return this.#request<ConnectionList>("/api/instagram/connections", { method: "POST", body: JSON.stringify({ list, ...(cursor ? { cursor } : {}) }) }, signal); }
  async events(taskId: string, lastEventId: string | undefined, onEvent: (event: TaskEvent) => void, signal: AbortSignal) { const response = await this.#fetch(`${this.#base}/api/agent/tasks/${encodeURIComponent(taskId)}/events`, { headers: { authorization: `Bearer ${this.#token()}`, ...(lastEventId ? { "last-event-id": lastEventId } : {}) }, signal }); if (!response.ok || !response.body) throw new ApiError("event_stream_error", "Live updates are unavailable", response.status); const reader = response.body.getReader(); const decoder = new TextDecoder(); let buffer = ""; while (!signal.aborted) { const chunk = await reader.read(); if (chunk.done) break; buffer += decoder.decode(chunk.value, { stream: true }); let boundary; while ((boundary = buffer.indexOf("\n\n")) >= 0) { const frame = buffer.slice(0, boundary); buffer = buffer.slice(boundary + 2); if (frame.startsWith(":")) continue; const data = frame.split("\n").find((line) => line.startsWith("data: "))?.slice(6); if (data) onEvent(JSON.parse(data) as TaskEvent); } } }
}
