import { Component, useEffect, useMemo, useRef, useState, type ErrorInfo, type ReactNode } from "react";
import { ApiClient, ApiError } from "./api-client.js";
import { TaskCache } from "./event-cache.js";
import type { Analytics, Approval, ConnectionList, ConnectionResult, ProfileContent, ReviewItem, Task, TaskEvent, TaskStatus } from "./types.js";

export interface DashboardClient { createTask(goal: string, signal?: AbortSignal): Promise<Task>; task(id: string, signal?: AbortSignal): Promise<Task>; cancel(id: string, signal?: AbortSignal): Promise<Task>; approval(id: string, signal?: AbortSignal): Promise<Approval>; decide(taskId: string, approval: Approval, decision: "approve" | "reject", signal?: AbortSignal): Promise<{ status: string; task: Task }>; analytics(category?: string, severity?: string, signal?: AbortSignal): Promise<Analytics>; comments(ids: readonly string[], signal?: AbortSignal): Promise<Record<string, unknown>[]>; reviews(signal?: AbortSignal): Promise<ReviewItem[]>; correct(commentId: string, correction: Record<string, unknown>, signal?: AbortSignal): Promise<ReviewItem>; collect(cursor?: string, followerCursor?: string, signal?: AbortSignal): Promise<ConnectionResult>; connections?(list: "followers" | "following", cursor?: string, signal?: AbortSignal): Promise<ConnectionList>; collectProfile?(username: string, cursor?: string, signal?: AbortSignal): Promise<ProfileContent>; events(taskId: string, lastEventId: string | undefined, onEvent: (event: TaskEvent) => void, signal: AbortSignal): Promise<void> }
class ErrorBoundary extends Component<{ children: ReactNode }, { failed: boolean }> { state = { failed: false }; static getDerivedStateFromError() { return { failed: true }; } componentDidCatch(error: Error, info: ErrorInfo) { console.error("Dashboard render failed", error, info.componentStack); } render() { return this.state.failed ? <main className="fatal" role="alert"><h1>Dashboard could not load</h1><p>Refresh the page. Your persisted tasks are safe.</p></main> : this.props.children; } }
const labels: Record<TaskStatus, string> = { queued: "Queued", running: "Running", approval_required: "Waiting for approval", completed: "Completed", failed: "Failed", cancelled: "Cancelled", safely_blocked: "Safely blocked" };
const errorText = (error: unknown) => error instanceof ApiError ? `${error.message}${error.requestId ? ` · Request ${error.requestId}` : ""}` : error instanceof Error ? error.message : "Something went wrong";
export const resolveInitialToken = (configured: string, stored: string | null) => configured || stored || "";

function useRoute() { const read = () => window.location.hash.slice(1) || "/tasks"; const [route, setRoute] = useState(read); useEffect(() => { const update = () => setRoute(read()); window.addEventListener("hashchange", update); return () => window.removeEventListener("hashchange", update); }, []); return route; }
function Shell({ children }: { children: ReactNode }) { const route = useRoute(); return <div className="app-shell"><aside><a className="brand" href="#/tasks"><span>IA</span><strong>Insight Agent</strong></a><nav aria-label="Primary navigation">{[["/tasks", "Tasks"], ["/analytics", "Analytics"], ["/reviews", "Human review"], ["/connections", "Connections"]].map(([path, name]) => <a key={path} href={`#${path}`} aria-current={route === path ? "page" : undefined}>{name}</a>)}</nav><p className="local-note">Local-first · authorized data only</p></aside><div className="workspace"><header className="topbar"><div><p className="eyebrow">Instagram intelligence</p><h1>{route === "/analytics" ? "Comment analytics" : route === "/reviews" ? "Human review" : route === "/connections" ? "Connection explorer" : "Agent tasks"}</h1></div><span className="secure">● Local session</span></header>{children}</div></div>; }

function TaskPage({ client }: { client: DashboardClient }) { const [goal, setGoal] = useState(""); const [task, setTask] = useState<Task>(); const [profile, setProfile] = useState<ProfileContent>(); const [events, setEvents] = useState<TaskEvent[]>([]); const [approval, setApproval] = useState<Approval>(); const [busy, setBusy] = useState(false); const [error, setError] = useState(""); const cache = useMemo(() => new TaskCache(), [task?.taskId]);
  const collectEntireProfile = async (username: string) => { if (!client.collectProfile) throw new Error("Profile collection is unavailable"); let result = await client.collectProfile(username); const resolvedUsername = result.username; const posts = new Map(result.posts.map((post) => [post.postId, post])); for (let page = 1; result.nextCursor && page < 20; page += 1) { const next = await client.collectProfile(resolvedUsername, result.nextCursor); for (const post of next.posts) posts.set(post.postId, post); if (next.nextCursor === result.nextCursor) { result = { ...next, nextCursor: null }; break; } result = next; } return { ...result, posts: [...posts.values()] }; };
  useEffect(() => { if (!task || ["completed", "failed", "cancelled", "safely_blocked"].includes(task.status)) return; const controller = new AbortController(); let stopped = false; const connect = async () => { while (!stopped) { try { await client.events(task.taskId, cache.lastEventId, (event) => { cache.add(event); setEvents([...cache.events]); void client.task(task.taskId).then((next) => setTask(cache.reconcile(next))); }, controller.signal); } catch { if (!controller.signal.aborted) await new Promise((resolve) => setTimeout(resolve, 500)); } } }; void connect(); return () => { stopped = true; controller.abort(); }; }, [client, task?.taskId, task?.status, cache]);
  useEffect(() => { if (task?.status !== "approval_required") { setApproval(undefined); return; } const controller = new AbortController(); void client.approval(task.taskId, controller.signal).then(setApproval).catch((reason) => setError(errorText(reason))); return () => controller.abort(); }, [client, task?.taskId, task?.status]);
  const submit = async () => { const clean = goal.trim(); if (!clean || clean.length > 4000 || busy) return; setBusy(true); setError(""); try { const match = /(?:posts?|pictures?|photos?|images?)(?:\s+and\s+(?:posts?|pictures?|photos?|images?))?\s+(?:of|from)\s+@?([A-Za-z0-9._-]{1,64})/i.exec(clean); if (match?.[1] && client.collectProfile) { setTask(undefined); setEvents([]); setProfile(await collectEntireProfile(match[1])); } else { const created = await client.createTask(clean); setTask(created); setProfile(undefined); cache.reconcile(created); setEvents([]); } setGoal(""); } catch (reason) { setError(errorText(reason)); } finally { setBusy(false); } };
  const decide = async (decision: "approve" | "reject") => { if (!task || !approval || busy) return; setBusy(true); setError(""); try { const result = await client.decide(task.taskId, approval, decision); setTask(result.task); setApproval(undefined); } catch (reason) { setError(errorText(reason)); } finally { setBusy(false); } };
  if (profile) return <main className="content"><section className="panel profile-results" aria-live="polite"><div className="panel-head"><div><p className="section-label">Profile content</p><h1>@{profile.username}</h1></div><div className="actions"><strong>{profile.posts.length} posts loaded</strong><button className="ghost" onClick={() => setProfile(undefined)}>New search</button></div></div><div className="profile-post-grid">{profile.posts.map((post) => <article className="profile-post" key={post.postId}>{post.mediaUrl && <a href={post.url} target="_blank" rel="noreferrer"><img src={post.mediaUrl} alt={post.caption ? `Post by @${profile.username}: ${post.caption}` : `Post by @${profile.username}`}/></a>}<div><a href={post.url} target="_blank" rel="noreferrer"><strong>@{profile.username}</strong></a>{post.caption && <p>{post.caption}</p>}<small>{new Date(post.publishedAt).toLocaleString()}</small><h2>{post.comments.length} comments</h2><ul>{post.comments.map((comment) => <li key={comment.commentId}><strong>{comment.author ? `@${comment.author}` : "Instagram user"}</strong><p>{comment.text}</p></li>)}</ul></div></article>)}</div>{profile.nextCursor && client.collectProfile && <button disabled={busy} onClick={() => { setBusy(true); void client.collectProfile!(profile.username, profile.nextCursor ?? undefined).then((next) => setProfile({ ...next, posts: [...profile.posts, ...next.posts] })).catch((reason) => setError(errorText(reason))).finally(() => setBusy(false)); }}>{busy ? "Loading…" : "Load more posts"}</button>}{error && <p className="alert" role="alert">{error}</p>}</section></main>;
  return <main className="content"><section className="goal-card" aria-labelledby="goal-heading"><div><p className="section-label">New task</p><h2 id="goal-heading">What should the agent investigate?</h2></div><label htmlFor="goal">Natural-language goal</label><textarea id="goal" value={goal} maxLength={4000} onChange={(event) => setGoal(event.target.value)} placeholder="Analyze recent comments and summarize the most severe delivery complaints…"/><div className="form-footer"><span>{goal.length}/4000</span><button disabled={busy || !goal.trim()} onClick={submit}>{busy ? "Submitting…" : "Start task"}</button></div>{error && <p className="alert" role="alert">{error}</p>}</section>{task ? <section className="task-grid" aria-live="polite"><article className="panel task-main"><div className="panel-head"><div><p className="section-label">Current task</p><h2>{task.goal}</h2></div><span className={`status status-${task.status}`}>{labels[task.status]}</span></div><p className="current-action">{task.currentAction ? `Now: ${task.currentAction}` : task.finalResponse ?? task.terminalReason ?? "Waiting for the next durable update."}</p><div className="progress"><span style={{ width: task.status === "completed" ? "100%" : task.status === "queued" ? "12%" : `${Math.min(90, 24 + task.steps.length * 12)}%` }}/></div>{!["completed", "failed", "cancelled", "safely_blocked"].includes(task.status) && <button className="danger ghost" disabled={busy} onClick={() => { setBusy(true); void client.cancel(task.taskId).then(setTask).catch((reason) => setError(errorText(reason))).finally(() => setBusy(false)); }}>Cancel task</button>}</article>{task.status === "approval_required" && <article className="panel approval"><p className="section-label">Explicit approval required</p><h2>Sensitive action paused</h2>{approval ? <><p><strong>Risk: {approval.risk}</strong></p><p>{approval.explanation}</p><p className="muted">Expires {new Date(approval.expiresAt).toLocaleString()}</p><div className="actions"><button disabled={busy} onClick={() => decide("approve")}>Approve action</button><button className="danger" disabled={busy} onClick={() => decide("reject")}>Reject</button></div></> : <p>Loading approval details…</p>}<p className="muted">No action executes until the server confirms approval.</p></article>}<article className="panel activity"><div className="panel-head"><h2>Activity</h2><span>{events.length} events</span></div>{events.length === 0 ? <p className="empty">Updates will appear here as the task runs.</p> : <ol>{events.map((event) => <li key={event.id}><span className="event-dot"/><div><strong>{event.type.replaceAll(".", " ")}</strong><time dateTime={event.occurredAt}>{new Date(event.occurredAt).toLocaleTimeString()}</time></div></li>)}</ol>}</article></section> : <section className="empty-state"><span>⌁</span><h2>No active task</h2><p>Enter a goal above to create a durable, supervised agent task.</p></section>}</main>; }

function AnalyticsPage({ client }: { client: DashboardClient }) { const [data, setData] = useState<Analytics>(); const [category, setCategory] = useState(""); const [severity, setSeverity] = useState(""); const [sources, setSources] = useState<Record<string, unknown>[]>(); const [error, setError] = useState(""); useEffect(() => { const controller = new AbortController(); void client.analytics(category, severity, controller.signal).then(setData).catch((reason) => setError(errorText(reason))); return () => controller.abort(); }, [client, category, severity]); const total = Object.values(data?.sentiment ?? {}).reduce((sum, count) => sum + count, 0); return <main className="content"><section className="filters" aria-label="Analytics filters"><label>Category<select value={category} onChange={(e) => setCategory(e.target.value)}><option value="">All</option><option value="product_quality">Product quality</option><option value="delivery">Delivery</option><option value="pricing">Pricing</option><option value="customer_service">Customer service</option></select></label><label>Severity<select value={severity} onChange={(e) => setSeverity(e.target.value)}><option value="">All</option><option>low</option><option>medium</option><option>high</option><option>critical</option></select></label></section>{error && <p role="alert" className="alert">{error}</p>}<section className="metric-grid" aria-label="Sentiment totals">{Object.entries(data?.sentiment ?? {}).map(([name, count]) => <article className="metric" key={name}><span>{name}</span><strong>{count}</strong><small>{total ? Math.round(count / total * 100) : 0}% of analyzed</small></article>)}</section><section className="panel"><div className="panel-head"><div><p className="section-label">Evidence-backed</p><h2>Complaint groups</h2></div></div>{data?.groups.length ? <div className="group-list">{data.groups.map((group) => <article key={`${group.category}-${group.severity}`}><span className={`severity severity-${group.severity}`}>{group.severity}</span><h3>{group.category.replaceAll("_", " ")}</h3><strong>{group.count} comments</strong><button className="link" onClick={() => void client.comments(group.commentIds).then(setSources).catch((reason) => setError(errorText(reason)))}>Open supporting records</button></article>)}</div> : <p className="empty">No complaint groups match these filters.</p>}</section>{sources && <section className="panel evidence" aria-live="polite"><div className="panel-head"><h2>Supporting comments</h2><button className="ghost" onClick={() => setSources(undefined)}>Close</button></div><ul>{sources.map((source) => <li key={String(source.commentId)}><strong>{String(source.commentId)}</strong><p>{String(source.text ?? "Source record unavailable")}</p></li>)}</ul></section>}</main>; }

function ReviewsPage({ client }: { client: DashboardClient }) { const [items, setItems] = useState<ReviewItem[]>([]); const [saving, setSaving] = useState(""); const [error, setError] = useState(""); useEffect(() => { const controller = new AbortController(); void client.reviews(controller.signal).then(setItems).catch((reason) => setError(errorText(reason))); return () => controller.abort(); }, [client]); const save = async (item: ReviewItem, sentiment: string) => { setSaving(item.commentId); setError(""); try { const updated = await client.correct(item.commentId, { sentiment }); setItems((current) => current.map((entry) => entry.commentId === item.commentId ? updated : entry)); } catch (reason) { setError(errorText(reason)); } finally { setSaving(""); } }; return <main className="content">{error && <p className="alert" role="alert">{error}</p>}<section className="review-list">{items.length === 0 ? <div className="empty-state"><h2>Review queue is clear</h2><p>Low-confidence analyses will appear here.</p></div> : items.map((item) => <article className="panel review-card" key={item.commentId}><div className="panel-head"><div><p className="section-label">{item.commentId}</p><h2>{item.complaint ?? item.reason}</h2></div><span className="confidence">{Math.round(item.confidence * 100)}% confidence</span></div><dl><div><dt>Category</dt><dd>{item.complaintCategory}</dd></div><div><dt>Severity</dt><dd>{item.severity}</dd></div><div><dt>Language</dt><dd>{item.language}</dd></div></dl><label>Correct sentiment<select aria-label={`Correct sentiment for ${item.commentId}`} defaultValue={item.sentiment} disabled={saving === item.commentId} onChange={(event) => void save(item, event.target.value)}><option>positive</option><option>neutral</option><option>negative</option><option>mixed</option><option>unknown</option></select></label>{item.reviewStatus === "reviewed" && <p className="success" role="status">Saved with audit history ({item.history?.length ?? 0} correction)</p>}{item.original && <details><summary>Original model output</summary><pre>{JSON.stringify(item.original, null, 2)}</pre></details>}</article>)}</section></main>; }

function ConnectionsPage({ client }: { client: DashboardClient }) { const [result, setResult] = useState<ConnectionResult>(); const [busy, setBusy] = useState(false); const [error, setError] = useState(""); const collect = async (resume: boolean) => { if (busy) return; setBusy(true); setError(""); try { const next = await client.collect(resume ? result?.nextCursor ?? undefined : undefined, resume ? result?.followersNextCursor ?? undefined : undefined); setResult((previous) => resume && previous ? { ...next, followers: [...previous.followers, ...next.followers], accounts: [...previous.accounts, ...next.accounts] } : next); } catch (reason) { setError(errorText(reason)); } finally { setBusy(false); } }; return <main className="content"><section className="panel connection-intro"><div><p className="section-label">Bounded and resumable</p><h2>Followers and following comments</h2><p>Collect only content visible to your authorized Instagram session.</p></div><div className="actions"><button disabled={busy} onClick={() => void collect(false)}>{busy ? "Collecting…" : "Collect first batch"}</button>{(result?.nextCursor || result?.followersNextCursor) && <button className="ghost" disabled={busy} onClick={() => void collect(true)}>Load next batch</button>}</div>{error && <p className="alert" role="alert">{error}</p>}</section>{result && <><p className="muted">{result.followers.length} followers · {result.accounts.length} following loaded</p><section className="connection-grid"><article className="panel"><h2>Followers</h2><ul>{result.followers.map((account) => <li key={account.username}><strong>{account.displayName}</strong> <span>@{account.username}</span></li>)}</ul></article><div className="following-list">{result.accounts.map((account) => <article className="panel" key={account.username}><h2>{account.displayName} <small>@{account.username}</small></h2>{account.error ? <p className="alert">{account.error}</p> : account.posts.length === 0 ? <p className="empty">No accessible posts.</p> : account.posts.map((post) => <section className="connection-post" key={post.postId}><a href={post.url} target="_blank" rel="noreferrer">Post {post.postId}</a><ul>{post.comments.map((comment) => <li key={comment.commentId}><strong>{comment.author ? `@${comment.author}` : "Account"}</strong><p>{comment.text}</p></li>)}</ul></section>)}</article>)}</div></section></>}</main>; }
function ConnectionListsPage({ client }: { client: DashboardClient }) {
  const [mode, setMode] = useState<"followers" | "following">();
  const [result, setResult] = useState<ConnectionList>();
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState("");
  const [profile, setProfile] = useState<ProfileContent>();
  const activeRequest = useRef<AbortController | undefined>(undefined);
  const load = async (selected: "followers" | "following", resume = false) => {
    if (busy) return;
    const controller = new AbortController(); activeRequest.current = controller;
    setMode(selected); setBusy(true); setError("");
    try {
      const cursor = resume ? result?.nextCursor ?? undefined : undefined;
      const next = client.connections ? await client.connections(selected, cursor, controller.signal) : await client.collect(selected === "following" ? cursor : undefined, selected === "followers" ? cursor : undefined, controller.signal).then((legacy) => ({ accounts: selected === "followers" ? legacy.followers.map((item) => ({ ...item, profilePath: `/${item.username}/` })) : legacy.accounts.map(({ username, displayName }) => ({ username, displayName, profilePath: `/${username}/` })), nextCursor: selected === "followers" ? legacy.followersNextCursor : legacy.nextCursor }));
      setResult((previous) => resume && previous ? { ...next, accounts: [...previous.accounts, ...next.accounts] } : next);
    } catch (reason) { if (!controller.signal.aborted) setError(errorText(reason)); } finally { if (activeRequest.current === controller) activeRequest.current = undefined; setBusy(false); }
  };
  const openProfile = async (username: string) => {
    if (busy || !client.collectProfile) return;
    const controller = new AbortController(); activeRequest.current = controller;
    setBusy(true); setError(""); setProfile(undefined);
    try {
      let page = await client.collectProfile(username, undefined, controller.signal);
      const resolvedUsername = page.username;
      const posts = new Map(page.posts.map((post) => [post.postId, post]));
      for (let index = 1; page.nextCursor && index < 20; index += 1) {
        const next = await client.collectProfile(resolvedUsername, page.nextCursor, controller.signal);
        for (const post of next.posts) posts.set(post.postId, post);
        if (next.nextCursor === page.nextCursor) { page = { ...next, nextCursor: null }; break; }
        page = next;
      }
      setProfile({ ...page, posts: [...posts.values()] });
    } catch (reason) { if (!controller.signal.aborted) setError(errorText(reason)); }
    finally { if (activeRequest.current === controller) activeRequest.current = undefined; setBusy(false); }
  };
  const items = result?.accounts;
  const nextCursor = result?.nextCursor;
  return <main className="content"><section className="panel connection-intro"><div><p className="section-label">Your Instagram connections</p><h2>Choose a list</h2><p>Select a person to display all accessible pictures and comments.</p></div><div className="actions connection-tabs"><button aria-pressed={mode === "followers"} disabled={busy} onClick={() => void load("followers")}>Followers</button><button aria-pressed={mode === "following"} disabled={busy} onClick={() => void load("following")}>Following</button>{busy && <button className="danger" onClick={() => activeRequest.current?.abort()}>Stop</button>}</div>{error && <p className="alert" role="alert">{error}</p>}</section>{mode && <section className="panel connection-list" aria-live="polite"><div className="panel-head"><h2>{mode === "followers" ? "Followers" : "Following"}</h2><strong>{items?.length ?? 0} loaded</strong></div>{busy && !items ? <p>Loading {mode}…</p> : items?.length ? <ul>{items.map((account) => <li key={account.username}><button className="connection-person" disabled={busy} onClick={() => void openProfile(account.username)}><strong>{account.displayName}</strong><span>@{account.username}</span></button></li>)}</ul> : !busy && <p className="empty">No {mode} were found.</p>}{nextCursor && <button className="ghost" disabled={busy} onClick={() => void load(mode, true)}>{busy ? "Loading…" : "Load more"}</button>}</section>}{profile && <section className="panel profile-results connection-profile" aria-live="polite"><div className="panel-head"><div><p className="section-label">Selected profile</p><h2>@{profile.username}</h2></div><strong>{profile.posts.length} posts</strong></div>{profile.posts.length === 0 ? <p className="empty profile-empty">No posts are visible. This account may be private, empty, or inaccessible to your authorized Instagram session.</p> : <div className="profile-post-grid">{profile.posts.map((post) => <article className="profile-post" key={post.postId}>{post.mediaUrl && <a href={post.url} target="_blank" rel="noreferrer"><img src={post.mediaUrl} alt={post.caption ? `Post by @${profile.username}: ${post.caption}` : `Post by @${profile.username}`}/></a>}<div><a href={post.url} target="_blank" rel="noreferrer"><strong>@{profile.username}</strong></a>{post.caption && <p>{post.caption}</p>}<h3>{post.comments.length} comments</h3><ul>{post.comments.map((comment) => <li key={comment.commentId}><strong>{comment.author ? `@${comment.author}` : "Instagram user"}</strong><p>{comment.text}</p></li>)}</ul></div></article>)}</div>}</section>}</main>;
}
function Dashboard({ client }: { client: DashboardClient }) { const route = useRoute(); return <Shell>{route === "/analytics" ? <AnalyticsPage client={client}/> : route === "/reviews" ? <ReviewsPage client={client}/> : route === "/connections" ? <ConnectionListsPage client={client}/> : <TaskPage client={client}/>}</Shell>; }
export function App({ client }: { client?: DashboardClient }) { const configured = import.meta.env.VITE_API_TOKEN ?? ""; const [token, setToken] = useState(() => client ? "injected" : resolveInitialToken(configured, sessionStorage.getItem("instagram-agent-token"))); const resolved = useMemo(() => client ?? new ApiClient({ token: () => token }), [client, token]); if (!client && !token) return <main className="session-gate"><section className="panel"><p className="eyebrow">Local authentication</p><h1>Connect this dashboard</h1><p>Enter the bearer session configured as <code>API_SESSION_TOKEN</code>. It is stored only in this browser tab.</p><form onSubmit={(event) => { event.preventDefault(); const value = String(new FormData(event.currentTarget).get("token") ?? "").trim(); if (value) { sessionStorage.setItem("instagram-agent-token", value); setToken(value); } }}><label htmlFor="session-token">Local session token</label><input id="session-token" name="token" type="password" autoComplete="current-password" required/><button type="submit">Open dashboard</button></form></section></main>; return <ErrorBoundary><Dashboard client={resolved}/></ErrorBoundary>; }
