import { agentTaskStateSchema, type AgentTaskState } from "@instagram-agent/agent-core";
import type { DomainEvent } from "@instagram-agent/contracts";
import type { Db, Document, Filter } from "mongodb";
import type { ApiApprovalStore, ApiDataStore, ApiEventStore, ApiTaskStore } from "./platform.js";

type StoredEvent = DomainEvent & { userId: string; sequence: number };
export class MongoApiStore implements ApiTaskStore, ApiEventStore, ApiDataStore, ApiApprovalStore {
  constructor(readonly db: Db) {}
  async create(state: AgentTaskState) { const { steps: _steps, observations: _observations, errors: _errors, ...snapshot } = agentTaskStateSchema.parse(state); await this.db.collection("agent_tasks").insertOne(snapshot); }
  async get(userId: string, taskId: string) { const task = await this.db.collection("agent_tasks").findOne({ userId, taskId }, { projection: { _id: 0 } }); if (!task) return null; const steps = await this.db.collection("agent_steps").find({ userId, taskId }, { projection: { _id: 0, userId: 0, taskId: 0 } }).sort({ iteration: 1 }).toArray(); const observations = steps.flatMap((step) => step.observation ? [step.observation] : []); return agentTaskStateSchema.parse({ ...task, steps, observations, errors: observations.flatMap((item) => item.error ? [item.error] : []) }); }
  async update(userId: string, taskId: string, expectedRevision: number, mutate: (state: AgentTaskState) => AgentTaskState) { const current = await this.get(userId, taskId); if (!current || current.revision !== expectedRevision) return null; const next = agentTaskStateSchema.parse(mutate(current)); const { steps: _steps, observations: _observations, errors: _errors, ...snapshot } = next; const result = await this.db.collection("agent_tasks").replaceOne({ userId, taskId, revision: expectedRevision }, snapshot); return result.modifiedCount === 1 ? next : null; }
  async append(userId: string, event: DomainEvent) { const latest = await this.db.collection<StoredEvent>("agent_events").findOne({ userId, taskId: event.taskId }, { sort: { sequence: -1 }, projection: { sequence: 1 } }); await this.db.collection("agent_events").insertOne({ ...event, userId, sequence: (latest?.sequence ?? 0) + 1 }); }
  async after(userId: string, taskId: string, lastEventId?: string) { let sequence = 0; if (lastEventId) sequence = (await this.db.collection<StoredEvent>("agent_events").findOne({ userId, taskId, id: lastEventId }, { projection: { sequence: 1 } }))?.sequence ?? 0; return this.db.collection<StoredEvent>("agent_events").find({ userId, taskId, sequence: { $gt: sequence } }, { projection: { _id: 0, userId: 0, sequence: 0 } }).sort({ sequence: 1 }).toArray(); }
  async posts(userId: string, query: { cursor: number; limit: number; from?: string; to?: string }) { const filter: Filter<Document> = { userId, ...(query.from || query.to ? { publishedAt: { ...(query.from ? { $gte: new Date(query.from) } : {}), ...(query.to ? { $lte: new Date(query.to) } : {}) } } : {}) }; const collection = this.db.collection("instagram_posts"); const [items, total] = await Promise.all([collection.find(filter, { projection: { _id: 0 } }).sort({ publishedAt: -1 }).skip(query.cursor).limit(query.limit).toArray(), collection.countDocuments(filter)]); return { items, total }; }
  async comments(userId: string, query: { cursor: number; limit: number; postId?: string; sentiment?: string; commentIds?: readonly string[] }) { const filter: Filter<Document> = { userId, ...(query.postId ? { postId: query.postId } : {}), ...(query.sentiment ? { sentiment: query.sentiment } : {}), ...(query.commentIds ? { commentId: { $in: query.commentIds } } : {}) }; const collection = this.db.collection("instagram_comments"); const [items, total] = await Promise.all([collection.find(filter, { projection: { _id: 0 } }).sort({ publishedAt: -1, collectedAt: -1 }).skip(query.cursor).limit(query.limit).toArray(), collection.countDocuments(filter)]); return { items, total }; }
  async analytics(userId: string) { const [posts, comments, sentimentRows] = await Promise.all([this.db.collection("instagram_posts").countDocuments({ userId }), this.db.collection("instagram_comments").countDocuments({ userId }), this.db.collection("instagram_comments").aggregate<{ _id: string; count: number }>([{ $match: { userId } }, { $group: { _id: { $ifNull: ["$sentiment", "unknown"] }, count: { $sum: 1 } } }]).toArray()]); return { posts, comments, sentiment: Object.fromEntries(sentimentRows.map((row) => [row._id, row.count])), semantics: "Counts include the current user's stored records; missing sentiment is grouped as unknown." }; }
  async complaintGroups(userId: string, query: { category?: string; severity?: string }) { const match = { userId, sentiment: { $in: ["negative", "mixed"] }, ...(query.category ? { complaintCategory: query.category } : {}), ...(query.severity ? { severity: query.severity } : {}) }; const groups = await this.db.collection("comment_analysis").aggregate([{ $match: match }, { $group: { _id: { category: { $ifNull: ["$complaintCategory", "$category"] }, severity: "$severity" }, commentIds: { $addToSet: "$commentId" } } }, { $project: { _id: 0, category: "$_id.category", severity: "$_id.severity", commentIds: 1, count: { $size: "$commentIds" } } }]).toArray(); const sentimentRows = await this.db.collection("comment_analysis").aggregate<{ _id: string; count: number }>([{ $match: { userId, ...(query.category ? { complaintCategory: query.category } : {}), ...(query.severity ? { severity: query.severity } : {}) } }, { $group: { _id: "$sentiment", count: { $sum: 1 } } }]).toArray(); return { sentiment: Object.fromEntries(sentimentRows.map((row) => [row._id, row.count])), groups }; }
  async reviews(userId: string, limit: number) { return this.db.collection("comment_analysis").find({ userId, reviewStatus: "needs_review" }, { projection: { _id: 0 } }).sort({ confidence: 1, analyzedAt: 1 }).limit(limit).toArray(); }
  async correct(userId: string, commentId: string, correction: Record<string, unknown>, reviewerId: string) { const collection = this.db.collection("comment_analysis"); const current = await collection.findOne({ userId, commentId }, { projection: { _id: 0 } }); if (!current) return null; const reviewedAt = new Date(); const original = current.original ?? current; const history = [...(Array.isArray(current.history) ? current.history : []), { reviewerId, reviewedAt, correction }]; await collection.updateOne({ userId, commentId }, { $set: { ...correction, original, reviewStatus: "reviewed", reviewerId, reviewedAt, history } }); return collection.findOne({ userId, commentId }, { projection: { _id: 0 } }); }
  async pending(userId: string, taskId: string) { return this.db.collection("approvals").findOne({ userId, taskId, status: "pending", expiresAt: { $gt: new Date() } }, { projection: { _id: 0, userId: 0, taskId: 0 } }); }
  async decide(input: { userId: string; taskId: string; requestId: string; token: string; decision: "approve" | "reject" }) { const collection = this.db.collection("approvals"); const changed = await collection.findOneAndUpdate({ userId: input.userId, taskId: input.taskId, requestId: input.requestId, token: input.token, status: "pending", expiresAt: { $gt: new Date() } }, { $set: { status: input.decision === "approve" ? "approved" : "rejected", decidedAt: new Date() } }, { returnDocument: "after" }); if (changed) return changed.status as "approved" | "rejected"; const existing = await collection.findOne({ userId: input.userId, taskId: input.taskId, requestId: input.requestId, token: input.token }); if (!existing) return "not_found"; if (existing.expiresAt <= new Date()) return "expired"; return "duplicate"; }
}
