import { createTaskState, type AgentTaskState } from "@instagram-agent/agent-core";
import type { DomainEvent } from "@instagram-agent/contracts";
import type { FastifyInstance, FastifyReply, FastifyRequest } from "fastify";
import { redact, type AuditRepository, type MetricsRegistry } from "@instagram-agent/agent-core";

export interface ApiSession { readonly userId: string; readonly sessionId: string; readonly expiresAt: number }
export interface ApiAuthenticator { authenticate(token: string): Promise<ApiSession | null> }
export interface ApiTaskStore {
  create(state: AgentTaskState): Promise<void>;
  get(userId: string, taskId: string): Promise<AgentTaskState | null>;
  update(userId: string, taskId: string, expectedRevision: number, mutate: (state: AgentTaskState) => AgentTaskState): Promise<AgentTaskState | null>;
}
export interface ApiEventStore { append(userId: string, event: DomainEvent): Promise<void>; after(userId: string, taskId: string, lastEventId?: string): Promise<readonly DomainEvent[]> }
export interface ApiDataStore {
  posts(userId: string, query: { cursor: number; limit: number; from?: string; to?: string }): Promise<{ items: readonly Record<string, unknown>[]; total: number }>;
  comments(userId: string, query: { cursor: number; limit: number; postId?: string; sentiment?: string; commentIds?: readonly string[] }): Promise<{ items: readonly Record<string, unknown>[]; total: number }>;
  analytics(userId: string): Promise<Record<string, unknown>>;
  complaintGroups(userId: string, query: { category?: string; severity?: string }): Promise<Record<string, unknown>>;
  reviews(userId: string, limit: number): Promise<readonly Record<string, unknown>[]>;
  correct(userId: string, commentId: string, correction: Record<string, unknown>, reviewerId: string): Promise<Record<string, unknown> | null>;
}
export interface ApiApprovalStore { pending(userId: string, taskId: string): Promise<Record<string, unknown> | null>; decide(input: { userId: string; taskId: string; requestId: string; token: string; decision: "approve" | "reject" }): Promise<"approved" | "rejected" | "expired" | "duplicate" | "not_found"> }
export interface ApiPlatformOptions {
  readonly auth: ApiAuthenticator; readonly tasks: ApiTaskStore; readonly events: ApiEventStore; readonly data: ApiDataStore; readonly approvals: ApiApprovalStore;
  readonly ready?: () => Promise<boolean>; readonly enqueue?: (state: AgentTaskState) => Promise<void>; readonly cancel?: (userId: string, taskId: string) => void; readonly now?: () => string; readonly id?: () => string;
  readonly allowedOrigins?: readonly string[]; readonly rateLimit?: number; readonly rateWindowMs?: number; readonly heartbeatMs?: number;
  readonly metrics?: MetricsRegistry;
  readonly audit?: AuditRepository;
}

declare module "fastify" { interface FastifyRequest { apiSession?: ApiSession } }
const terminal = new Set(["completed", "failed", "cancelled", "safely_blocked"]);
const envelope = (code: string, message: string, requestId?: string, details?: unknown) => ({ error: { code, message, ...(details === undefined ? {} : { details }), ...(requestId ? { requestId } : {}) } });
const integer = (value: unknown, fallback: number, maximum: number) => { const parsed = value === undefined ? fallback : Number(value); return Number.isInteger(parsed) && parsed >= 0 && parsed <= maximum ? parsed : null; };

export class StaticAuthenticator implements ApiAuthenticator {
  constructor(readonly sessions: ReadonlyMap<string, ApiSession>) {}
  async authenticate(token: string) { const session = this.sessions.get(token); return session && session.expiresAt > Date.now() ? session : null; }
}

export class InMemoryApiStore implements ApiTaskStore, ApiEventStore, ApiDataStore, ApiApprovalStore {
  readonly taskRecords = new Map<string, AgentTaskState>(); readonly eventRecords: Array<DomainEvent & { userId: string }> = [];
  readonly postRecords: Record<string, unknown>[] = []; readonly commentRecords: Record<string, unknown>[] = []; readonly analysisRecords: Record<string, unknown>[] = []; readonly approvalRecords = new Map<string, { userId: string; taskId: string; token: string; expiresAt: number; status: "pending" | "approved" | "rejected" }>();
  #key(userId: string, taskId: string) { return `${userId}\0${taskId}`; }
  async create(state: AgentTaskState) { const key = this.#key(state.userId, state.taskId); if (this.taskRecords.has(key)) throw new Error("duplicate_task"); this.taskRecords.set(key, structuredClone(state)); }
  async save(state: AgentTaskState) { this.taskRecords.set(this.#key(state.userId, state.taskId), structuredClone(state)); }
  async get(userId: string, taskId: string) { const value = this.taskRecords.get(this.#key(userId, taskId)); return value ? structuredClone(value) : null; }
  async update(userId: string, taskId: string, expectedRevision: number, mutate: (state: AgentTaskState) => AgentTaskState) { const key = this.#key(userId, taskId); const current = this.taskRecords.get(key); if (!current || current.revision !== expectedRevision) return null; const next = mutate(structuredClone(current)); this.taskRecords.set(key, structuredClone(next)); return next; }
  async append(userId: string, event: DomainEvent) { if (!this.taskRecords.has(this.#key(userId, event.taskId))) throw new Error("event_task_missing"); this.eventRecords.push({ ...event, userId }); }
  async after(userId: string, taskId: string, lastEventId?: string) { const scoped = this.eventRecords.filter((event) => event.userId === userId && event.taskId === taskId); if (!lastEventId) return scoped; const index = scoped.findIndex(({ id }) => id === lastEventId); return index < 0 ? scoped : scoped.slice(index + 1); }
  async posts(userId: string, query: { cursor: number; limit: number; from?: string; to?: string }) { const all = this.postRecords.filter((item) => item.userId === userId && (!query.from || String(item.publishedAt) >= query.from) && (!query.to || String(item.publishedAt) <= query.to)).sort((a, b) => String(b.publishedAt).localeCompare(String(a.publishedAt))); return { items: all.slice(query.cursor, query.cursor + query.limit), total: all.length }; }
  async comments(userId: string, query: { cursor: number; limit: number; postId?: string; sentiment?: string; commentIds?: readonly string[] }) { const all = this.commentRecords.filter((item) => item.userId === userId && (!query.postId || item.postId === query.postId) && (!query.sentiment || item.sentiment === query.sentiment) && (!query.commentIds || query.commentIds.includes(String(item.commentId)))).sort((a, b) => String(b.publishedAt ?? b.collectedAt).localeCompare(String(a.publishedAt ?? a.collectedAt))); return { items: all.slice(query.cursor, query.cursor + query.limit), total: all.length }; }
  async analytics(userId: string) { const posts = this.postRecords.filter((item) => item.userId === userId); const comments = this.commentRecords.filter((item) => item.userId === userId); const sentiment = comments.reduce<Record<string, number>>((counts, item) => { const key = String(item.sentiment ?? "unknown"); counts[key] = (counts[key] ?? 0) + 1; return counts; }, {}); return { posts: posts.length, comments: comments.length, sentiment, semantics: "Counts include the current user's stored records; missing sentiment is grouped as unknown." }; }
  async complaintGroups(userId: string, query: { category?: string; severity?: string }) { const analyses = this.analysisRecords.filter((item) => item.userId === userId && (!query.category || item.complaintCategory === query.category) && (!query.severity || item.severity === query.severity)); const groups = new Map<string, { category: string; severity: string; count: number; commentIds: string[] }>(); for (const item of analyses.filter((item) => item.sentiment === "negative" || item.sentiment === "mixed")) { const category = String(item.complaintCategory ?? "unknown"); const severity = String(item.severity ?? "none"); const key = `${category}\0${severity}`; const group = groups.get(key) ?? { category, severity, count: 0, commentIds: [] }; if (!group.commentIds.includes(String(item.commentId))) { group.commentIds.push(String(item.commentId)); group.count += 1; } groups.set(key, group); } const sentiment = analyses.reduce<Record<string, number>>((counts, item) => { const key = String(item.sentiment ?? "unknown"); counts[key] = (counts[key] ?? 0) + 1; return counts; }, {}); return { sentiment, groups: [...groups.values()] }; }
  async reviews(userId: string, limit: number) { return this.analysisRecords.filter((item) => item.userId === userId && item.reviewStatus === "needs_review").slice(0, limit).map((item) => structuredClone(item)); }
  async correct(userId: string, commentId: string, correction: Record<string, unknown>, reviewerId: string) { const item = this.analysisRecords.find((record) => record.userId === userId && record.commentId === commentId); if (!item) return null; const reviewedAt = new Date().toISOString(); const original = item.original ?? structuredClone(item); const history = Array.isArray(item.history) ? item.history : []; Object.assign(item, correction, { original, reviewStatus: "reviewed", reviewerId, reviewedAt, history: [...history, { reviewerId, reviewedAt, correction }] }); return structuredClone(item); }
  async pending(userId: string, taskId: string) { const entry = [...this.approvalRecords.entries()].find(([, record]) => record.userId === userId && record.taskId === taskId && record.status === "pending"); return entry ? { requestId: entry[0], token: entry[1].token, expiresAt: entry[1].expiresAt, risk: "sensitive", explanation: "This action requires explicit confirmation before execution." } : null; }
  async decide(input: { userId: string; taskId: string; requestId: string; token: string; decision: "approve" | "reject" }) { const record = this.approvalRecords.get(input.requestId); if (!record || record.userId !== input.userId || record.taskId !== input.taskId || record.token !== input.token) return "not_found"; if (record.expiresAt <= Date.now()) return "expired"; if (record.status !== "pending") return "duplicate"; record.status = input.decision === "approve" ? "approved" : "rejected"; return record.status; }
}

export function registerPlatform(app: FastifyInstance, options: ApiPlatformOptions): void {
  const now = options.now ?? (() => new Date().toISOString()); const id = options.id ?? (() => crypto.randomUUID());
  const rates = new Map<string, { start: number; count: number }>(); const allowedOrigins = new Set(options.allowedOrigins ?? ["http://localhost:5173"]);
  app.addHook("onRequest", async (request, reply) => {
    const origin = request.headers.origin; if (origin && !allowedOrigins.has(origin)) return reply.code(403).send(envelope("origin_denied", "Origin is not allowed", request.id));
    const key = request.ip; const timestamp = Date.now(); const entry = rates.get(key); const windowMs = options.rateWindowMs ?? 60_000; const next = !entry || timestamp - entry.start >= windowMs ? { start: timestamp, count: 1 } : { ...entry, count: entry.count + 1 }; rates.set(key, next); if (next.count > (options.rateLimit ?? 120)) return reply.code(429).send(envelope("rate_limited", "Request limit exceeded", request.id));
    if (!request.url.startsWith("/api/")) return;
    const header = request.headers.authorization; if (!header?.startsWith("Bearer ")) return reply.code(401).send(envelope("authentication_required", "A valid bearer session is required", request.id));
    const session = await options.auth.authenticate(header.slice(7)); if (!session) return reply.code(401).send(envelope("invalid_session", "Session is invalid or expired", request.id)); request.apiSession = session;
  });
  app.addHook("onSend", async (request, reply, payload) => { const origin = request.headers.origin; if (origin && allowedOrigins.has(origin)) { reply.header("access-control-allow-origin", origin); reply.header("vary", "origin"); } reply.header("x-content-type-options", "nosniff"); reply.header("x-frame-options", "DENY"); return payload; });
  app.addHook("onResponse", async (request, reply) => { options.metrics?.increment("http_requests_total", { method: request.method, route: request.routeOptions.url ?? "unknown", status: String(reply.statusCode) }); options.metrics?.observe("http_request_duration_ms", reply.elapsedTime, { route: request.routeOptions.url ?? "unknown" }); if (reply.statusCode >= 400) options.metrics?.increment("errors_total", { component: "api", status: String(reply.statusCode) }); });
  app.setErrorHandler((error, request, reply) => { const bodyLimit = (error as { code?: string }).code === "FST_ERR_CTP_BODY_TOO_LARGE"; reply.code(bodyLimit ? 413 : 500).send(envelope(bodyLimit ? "body_too_large" : "internal_error", bodyLimit ? "Request body exceeds the configured limit" : "The request could not be completed", request.id)); });
  app.get("/ready", async (_request, reply) => (await (options.ready?.() ?? Promise.resolve(true))) ? { status: "ready" } : reply.code(503).send(envelope("not_ready", "A required dependency is unavailable")));
  app.post("/api/agent/tasks", async (request, reply) => { const userId = request.apiSession!.userId; const text = (request.body as { goal?: unknown } | null)?.goal; if (typeof text !== "string" || text.trim().length < 1 || text.length > 4_000) return reply.code(400).send(envelope("invalid_goal", "Goal must contain 1 to 4000 characters", request.id)); const state = createTaskState({ taskId: id(), userId, sessionId: request.apiSession!.sessionId, text: text.trim() }, now()); try { await options.tasks.create(state); } catch { return reply.code(409).send(envelope("duplicate_task", "Task already exists", request.id)); } await options.events.append(userId, { id: id(), taskId: state.taskId, type: "task.queued", occurredAt: state.createdAt, payload: { revision: state.revision } }); await options.audit?.append({ auditId: id(), userId, taskId: state.taskId, occurredAt: state.createdAt, actor: "user", action: "task.created", status: "queued", data: redact({ goal: state.goal, requestId: request.id }) }); if (options.enqueue) void options.enqueue(state); return reply.code(202).send({ data: state }); });
  app.get("/api/agent/tasks/:taskId", async (request, reply) => { const state = await options.tasks.get(request.apiSession!.userId, (request.params as { taskId: string }).taskId); return state ? { data: state } : reply.code(404).send(envelope("task_not_found", "Task was not found", request.id)); });
  app.get("/api/agent/tasks/:taskId/status", async (request, reply) => { const state = await options.tasks.get(request.apiSession!.userId, (request.params as { taskId: string }).taskId); return state ? { data: { taskId: state.taskId, status: state.status, currentAction: state.currentAction, revision: state.revision, updatedAt: state.updatedAt } } : reply.code(404).send(envelope("task_not_found", "Task was not found", request.id)); });
  app.get("/api/agent/tasks/:taskId/steps", async (request, reply) => { const state = await options.tasks.get(request.apiSession!.userId, (request.params as { taskId: string }).taskId); if (!state) return reply.code(404).send(envelope("task_not_found", "Task was not found", request.id)); const query = request.query as Record<string, unknown>; const cursor = integer(query.cursor, 0, 1_000_000); const limit = integer(query.limit, 50, 100); if (cursor === null || limit === null || limit < 1) return reply.code(400).send(envelope("invalid_pagination", "Pagination is invalid", request.id)); const ordered = [...state.steps].sort((a, b) => a.iteration - b.iteration); return { data: ordered.slice(cursor, cursor + limit), page: { cursor, nextCursor: cursor + limit < ordered.length ? cursor + limit : null, total: ordered.length } }; });
  app.post("/api/agent/tasks/:taskId/cancel", async (request, reply) => { const userId = request.apiSession!.userId; const taskId = (request.params as { taskId: string }).taskId; const state = await options.tasks.get(userId, taskId); if (!state) return reply.code(404).send(envelope("task_not_found", "Task was not found", request.id)); if (terminal.has(state.status)) return reply.code(409).send(envelope("task_terminal", "Terminal tasks cannot be cancelled", request.id)); const at = now(); const updated = await options.tasks.update(userId, taskId, state.revision, (current) => ({ ...current, status: "cancelled", currentAction: null, terminalReason: "Cancelled by user", updatedAt: at, revision: current.revision + 1 })); if (!updated) return reply.code(409).send(envelope("task_conflict", "Task changed before cancellation", request.id)); options.cancel?.(userId, taskId); await options.events.append(userId, { id: id(), taskId, type: "task.cancelled", occurredAt: at, payload: { revision: updated.revision } }); await options.audit?.append({ auditId: id(), userId, taskId, occurredAt: at, actor: "user", action: "task.cancelled", status: "cancelled", data: { requestId: request.id, revision: updated.revision } }); return { data: updated }; });
  app.post("/api/agent/tasks/:taskId/approvals/:requestId", async (request, reply) => { const params = request.params as { taskId: string; requestId: string }; const body = request.body as { token?: unknown; decision?: unknown } | null; if (typeof body?.token !== "string" || (body.decision !== "approve" && body.decision !== "reject")) return reply.code(400).send(envelope("invalid_approval", "Token and approve/reject decision are required", request.id)); const userId = request.apiSession!.userId; const task = await options.tasks.get(userId, params.taskId); if (!task) return reply.code(404).send(envelope("task_not_found", "Task was not found", request.id)); if (terminal.has(task.status)) return reply.code(409).send(envelope("task_terminal", "Terminal tasks cannot accept approval decisions", request.id)); const status = await options.approvals.decide({ userId, taskId: params.taskId, requestId: params.requestId, token: body.token, decision: body.decision }); const codes = { expired: 410, duplicate: 409, not_found: 404 } as const; if (status in codes) return reply.code(codes[status as keyof typeof codes]).send(envelope(`approval_${status}`, `Approval is ${status.replace("_", " ")}`, request.id)); const at = now(); const next = await options.tasks.update(userId, params.taskId, task.revision, (current) => ({ ...current, status: status === "approved" ? "queued" : "cancelled", currentAction: null, terminalReason: status === "approved" ? undefined : "Approval rejected by user", updatedAt: at, revision: current.revision + 1 })); if (!next) return reply.code(409).send(envelope("task_conflict", "Task changed before the approval decision", request.id)); await options.events.append(userId, { id: id(), taskId: params.taskId, type: `approval.${status}`, occurredAt: at, payload: { requestId: params.requestId, revision: next.revision } }); await options.audit?.append({ auditId: id(), userId, taskId: params.taskId, occurredAt: at, actor: "user", action: `approval.${status}`, status, data: { requestId: params.requestId, revision: next.revision } }); if (status === "approved" && options.enqueue) void options.enqueue(next); return { data: { requestId: params.requestId, status, task: next } }; });
  app.get("/api/agent/tasks/:taskId/approval", async (request, reply) => { const taskId = (request.params as { taskId: string }).taskId; const userId = request.apiSession!.userId; const task = await options.tasks.get(userId, taskId); if (!task) return reply.code(404).send(envelope("task_not_found", "Task was not found", request.id)); const approval = await options.approvals.pending(userId, taskId); return approval ? { data: approval } : reply.code(404).send(envelope("approval_not_found", "No pending approval exists", request.id)); });
  const queryData = (kind: "posts" | "comments") => async (request: FastifyRequest, reply: FastifyReply) => { const query = request.query as Record<string, unknown>; const cursor = integer(query.cursor, 0, 1_000_000); const limit = integer(query.limit, 50, 100); const commentIds = typeof query.commentIds === "string" && query.commentIds ? query.commentIds.split(",") : undefined; if (cursor === null || limit === null || limit < 1 || (commentIds && (commentIds.length > 100 || commentIds.some((id) => !id || id.length > 200)))) return reply.code(400).send(envelope("invalid_pagination", "Pagination or evidence IDs are invalid", request.id)); const result = kind === "posts" ? await options.data.posts(request.apiSession!.userId, { cursor, limit, ...(typeof query.from === "string" ? { from: query.from } : {}), ...(typeof query.to === "string" ? { to: query.to } : {}) }) : await options.data.comments(request.apiSession!.userId, { cursor, limit, ...(typeof query.postId === "string" ? { postId: query.postId } : {}), ...(typeof query.sentiment === "string" ? { sentiment: query.sentiment } : {}), ...(commentIds ? { commentIds } : {}) }); return { data: result.items, page: { cursor, nextCursor: cursor + limit < result.total ? cursor + limit : null, total: result.total } }; };
  app.get("/api/posts", queryData("posts")); app.get("/api/comments", queryData("comments")); app.get("/api/analytics/summary", async (request) => ({ data: await options.data.analytics(request.apiSession!.userId) }));
  app.get("/api/analytics/complaints", async (request) => { const query = request.query as Record<string, unknown>; return { data: await options.data.complaintGroups(request.apiSession!.userId, { ...(typeof query.category === "string" ? { category: query.category } : {}), ...(typeof query.severity === "string" ? { severity: query.severity } : {}) }) }; });
  app.get("/api/diagnostics", async () => ({ data: options.metrics?.snapshot() ?? { counters: {}, gauges: {}, durations: {} } }));
  app.get("/api/reviews", async (request, reply) => { const limit = integer((request.query as Record<string, unknown>).limit, 25, 100); return limit === null || limit < 1 ? reply.code(400).send(envelope("invalid_pagination", "Review limit is invalid", request.id)) : { data: await options.data.reviews(request.apiSession!.userId, limit) }; });
  app.patch("/api/reviews/:commentId", async (request, reply) => { const body = request.body as { correction?: unknown } | null; if (!body?.correction || typeof body.correction !== "object" || Array.isArray(body.correction)) return reply.code(400).send(envelope("invalid_correction", "A correction object is required", request.id)); const correction = body.correction as Record<string, unknown>; const allowed = new Set(["sentiment", "confidence", "reason", "complaintCategory", "severity", "language", "complaint"]); const enums: Record<string, readonly string[]> = { sentiment: ["positive", "neutral", "negative", "mixed", "unknown"], severity: ["none", "low", "medium", "high", "critical"], language: ["english", "roman_urdu", "mixed", "other", "unknown"], complaintCategory: ["product_quality", "delivery", "pricing", "customer_service", "availability", "safety", "other", "unknown"] }; const invalid = Object.keys(correction).some((key) => !allowed.has(key)) || Object.entries(enums).some(([key, values]) => key in correction && !values.includes(String(correction[key]))) || ("confidence" in correction && (typeof correction.confidence !== "number" || correction.confidence < 0 || correction.confidence > 1)) || ("reason" in correction && (typeof correction.reason !== "string" || correction.reason.length < 1 || correction.reason.length > 500)) || ("complaint" in correction && correction.complaint !== null && typeof correction.complaint !== "string"); if (invalid) return reply.code(400).send(envelope("invalid_correction", "Correction values are invalid", request.id)); const result = await options.data.correct(request.apiSession!.userId, (request.params as { commentId: string }).commentId, correction, request.apiSession!.userId); return result ? { data: result } : reply.code(404).send(envelope("review_not_found", "Review record was not found", request.id)); });
  app.get("/api/agent/tasks/:taskId/events", async (request, reply) => { const taskId = (request.params as { taskId: string }).taskId; const userId = request.apiSession!.userId; if (!await options.tasks.get(userId, taskId)) return reply.code(404).send(envelope("task_not_found", "Task was not found", request.id)); let cursor = typeof request.headers["last-event-id"] === "string" ? request.headers["last-event-id"] : undefined; const events = await options.events.after(userId, taskId, cursor); reply.hijack(); reply.raw.writeHead(200, { "content-type": "text/event-stream; charset=utf-8", "cache-control": "no-cache", connection: "keep-alive", "x-accel-buffering": "no" }); for (const event of events) { reply.raw.write(`id: ${event.id}\nevent: ${event.type}\ndata: ${JSON.stringify(event)}\n\n`); cursor = event.id; } reply.raw.write(`: heartbeat ${Date.now()}\n\n`); let polling = false; const timer = setInterval(async () => { if (polling || reply.raw.destroyed) return; polling = true; try { const fresh = await options.events.after(userId, taskId, cursor); for (const event of fresh) { reply.raw.write(`id: ${event.id}\nevent: ${event.type}\ndata: ${JSON.stringify(event)}\n\n`); cursor = event.id; } reply.raw.write(`: heartbeat ${Date.now()}\n\n`); } finally { polling = false; } }, options.heartbeatMs ?? 15_000); request.raw.once("close", () => clearInterval(timer)); });
}
