import { agentTaskStateSchema, type AgentTaskState, type AuditRecord, type AuditRepository, type RecoveryStore } from "@instagram-agent/agent-core";
import type { Db, Document } from "mongodb";
import { MongoTaskRepository } from "./task-repository.js";

export class MongoRecoveryStore implements RecoveryStore { constructor(readonly db: Db) {} async findRecoverable(before: string) { const snapshots = await this.db.collection("agent_tasks").find({ status: { $in: ["running", "approval_required"] }, updatedAt: { $lt: before } }, { projection: { userId: 1, taskId: 1 } }).toArray(); const repository = new MongoTaskRepository(this.db); return (await Promise.all(snapshots.map((item) => repository.get(String(item.taskId), String(item.userId))))).filter((state): state is AgentTaskState => state !== null); } async replaceIfRevision(state: AgentTaskState, expectedRevision: number) { const parsed = agentTaskStateSchema.parse(state); const { steps: _steps, observations: _observations, errors: _errors, ...snapshot } = parsed; const result = await this.db.collection("agent_tasks").replaceOne({ userId: parsed.userId, taskId: parsed.taskId, revision: expectedRevision }, snapshot); return result.modifiedCount === 1; } }
export class MongoAuditRepository implements AuditRepository { constructor(readonly db: Db) {} async append(record: AuditRecord) { await this.db.collection("agent_audit").insertOne(record); } async forTask(userId: string, taskId: string) { return this.db.collection<AuditRecord & Document>("agent_audit").find({ userId, taskId }, { projection: { _id: 0 } }).sort({ occurredAt: 1, auditId: 1 }).toArray(); } }
export interface UserDataExport { readonly schemaVersion: 1; readonly userId: string; readonly exportedAt: string; readonly collections: Readonly<Record<string, readonly Record<string, unknown>[]>> }
const userCollections = ["agent_sessions", "agent_tasks", "agent_steps", "agent_events", "instagram_posts", "instagram_comments", "comment_analysis", "agent_memory", "approvals", "tool_invocations", "agent_audit"] as const;
export class UserDataLifecycle { constructor(readonly db: Db, readonly now: () => Date = () => new Date()) {} async export(userId: string): Promise<UserDataExport> { const entries = await Promise.all(userCollections.map(async (name) => [name, await this.db.collection(name).find({ userId }, { projection: { _id: 0 } }).toArray()] as const)); return { schemaVersion: 1, userId, exportedAt: this.now().toISOString(), collections: Object.fromEntries(entries) }; } async backup(userId: string) { return { format: "instagram-agent-local-backup", encrypted: false, warning: "Store this export on encrypted local media.", ...(await this.export(userId)) }; } async delete(userId: string) { const removed: Record<string, number> = {}; for (const name of userCollections) removed[name] = (await this.db.collection(name).deleteMany({ userId })).deletedCount; removed.users = (await this.db.collection("users").deleteMany({ userId })).deletedCount; return removed; } async purge(before: Date) { const retentionCollections = ["agent_events", "agent_audit", "tool_invocations"] as const; const removed: Record<string, number> = {}; for (const name of retentionCollections) removed[name] = (await this.db.collection(name).deleteMany({ occurredAt: { $lt: before } })).deletedCount; return removed; } }
